---
title: "Factors"
author: 
    name: "Monique Hernandez"
    affiliation: University of California, Santa Barbara
date: "Augustt 19, 2026"
format:
  html:
    toc: true
execute:
  message: false
  warning: false
---
[click here for github link](https://github.com/moniqueallyson/eds221day8) 

```{r, message=FALSE}
library(tidyverse)
library(ggplot2)

glimpse(gss_cat)
levels(gss_cat$rincome) 
```

## Boxplot with levels
```{r}
ggplot(
  data = gss_cat,
  mapping = aes(x = rincome)
) + # plus for to continue to plotting
  geom_bar() +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90))
```

## Plot without levels
```{r}
gss_cat |> # Changing to "alphabetical order"
  mutate(rincome = as.character(rincome)) |> # changing a column, as.character strips away the levels
  ggplot(
  mapping = aes(x = rincome)
) +
  geom_bar() +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90))
```

# Reordering 
```{r}
relig_summary <- gss_cat |> 
  summarize(tvhours = mean(tvhours, na.rm = TRUE),
.by = relig)
```

## Plot
```{r}
ggplot(
  data = relig_summary,
  mapping = aes(x = tvhours, y = relig)
) + 
  geom_point() # our categorical axis ir ordered by levels

```

## Plot
```{r}
ggplot(
  data = relig_summary,
  mapping = aes(x = tvhours, y = fct_reorder(relig, tvhours))
) + 
  geom_point()
```

## Factor Levels Count
```{r}
 gss_cat |> 
  count(partyid) #10 party affiliated categories
```

## Factor Collapse
```{r}
gss_cat |> 
  mutate(
    partyid = fct_collapse(
      partyid,
      "R" = c("Strong republican", "Not str republican"),
      "I" = c("Ind,near rep", "Ind,near dem", "Independent"),
      "D" = c("Strong democrat", "Not str democrat"),
      "O" = c("No answer", "Don't know", "Other party")
    )
  ) |> 
  count(partyid)
```